### ISSUE TITLE
Баг при использовании innerNavigation на нескольких табах в модуле tabbar-navigation.

### ISSUE THREAD

**Issue by vender98** [TouchInstinct/RoboSwag#60]
Модуль tabbar-navigation позволяет использовать внутреннюю навигацию внутри каждой табы (innerNavigation), а также обычную навигацию на уровне Activity (navigation).

Pre-conditions:
Необходимо иметь таббар с как минимум 2 табами, позволяющими снавигироваться на любой экран используя innerNavigation.

Test case:
1) Открыть первую вкладку
2) Снавигироваться на какой-нибудь экран в открытой вкладке. Необходимо использовать именно innerNavigation, то есть чтобы таббар остался видимым на открытом экране.
3) Открыть вторую вкладку.
4) Проделать все действия из шага 2.

В результате приложение крашится со следующим стектрейсом:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1532)
        at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1554)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:569)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:520)
        at ru.touchin.roboswag.components.navigation.FragmentNavigation.addToStack(FragmentNavigation.kt:115)
        at ru.touchin.roboswag.components.navigation.viewcontrollers.ViewControllerNavigation.pushViewController(ViewControllerNavigation.kt:64)
        at ru.touchin.roboswag.components.navigation.viewcontrollers.ViewControllerNavigation.pushViewController$default(ViewControllerNavigation.kt:62)

**Comment by vender98** [comment]
Fixed in https://github.com/TouchInstinct/RoboSwag/pull/63
